// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Api.Infrastructure.Data;

namespace Web.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181114005232_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Web.Api.Core.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<DateTime>("Created");

                    b.Property<string>("FirstName");

                    b.Property<int>("HeightCm");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("WeightKg");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new { Id = 1, BirthDate = new DateTime(1987, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 562, DateTimeKind.Utc), FirstName = "Sidney", HeightCm = 180, LastName = "Crosby", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 91m },
                        new { Id = 2, BirthDate = new DateTime(1997, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 563, DateTimeKind.Utc), FirstName = "Connor", HeightCm = 185, LastName = "McDavid", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 88m },
                        new { Id = 3, BirthDate = new DateTime(1997, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 563, DateTimeKind.Utc), FirstName = "Auston", HeightCm = 191, LastName = "Matthews", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 100m },
                        new { Id = 4, BirthDate = new DateTime(1988, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 563, DateTimeKind.Utc), FirstName = "Patrick", HeightCm = 180, LastName = "Kane", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 177m },
                        new { Id = 5, BirthDate = new DateTime(1989, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 563, DateTimeKind.Utc), FirstName = "Drew", HeightCm = 185, LastName = "Doughty", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 200m },
                        new { Id = 6, BirthDate = new DateTime(1990, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), Created = new DateTime(2018, 11, 14, 0, 52, 32, 563, DateTimeKind.Utc), FirstName = "Erik", HeightCm = 183, LastName = "Karlsson", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), WeightKg = 190m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
